### ISSUE TITLE
Intermediate temporary pcds write to build directory when stitching

### ISSUE THREAD

**Issue by nicole-cranon** [UCD-SeniorDesign-VolcanobotTeam2015/volcanobot#34]
Should probably be written to the output directory chosen by the user in the GUI.

**Comment by MattLamont** [comment]
This one should be easy. I only output those temp pcd files for debugging. I can get rid of that line of code and we won't have any temp pcd files being outputted anymore.

**Comment by nicole-cranon** [comment]
I did this in the mac_integration branch. thanks

**Comment by nicole-cranon** [comment]
@MattLamont didn't you make this change to develop as well?

**Comment by MattLamont** [comment]
Yep, the change has been merged into develop
